import type { CSSVariablesResolver } from "@mantine/core";

export const cssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    "--app-page-max-width": "var(--page-max-width)",
    "--app-card-padding": "var(--card-padding)",
    "--app-element-gap": "var(--element-gap)",
  },
  light: {
    "--app-surface-canvas": "var(--surface-canvas)",
    "--app-surface-card": "var(--surface-card)",
    "--app-surface-floating": "var(--surface-floating-preview)",
    "--app-surface-inverted": "var(--surface-inverted-section)",
    "--app-text-primary": "var(--color-terminal-ink)",
    "--app-text-secondary": "var(--color-terminal-soft)",
    "--app-text-muted": "var(--color-terminal-muted)",
    "--app-border-default": "var(--color-frost-line)",
    "--app-border-strong": "var(--color-frost-line-strong)",
    "--app-accent": "var(--color-signal)",
    "--app-accent-soft": "var(--color-signal-wash)",
    "--app-accent-hover": "var(--color-signal-dark)",
    "--app-accent-focus": "var(--color-signal-dark)",
    "--app-status-playing": "var(--color-signal-dark)",
    "--app-status-won": "var(--color-success)",
    "--app-status-dead": "var(--color-danger)",
    "--app-terminal-glow": "rgba(39, 185, 214, 0.12)",
  },
  dark: {
    "--app-surface-canvas": "var(--surface-dark-canvas)",
    "--app-surface-card": "var(--surface-dark-card)",
    "--app-surface-floating": "var(--surface-dark-floating)",
    "--app-surface-inverted": "var(--color-terminal-light)",
    "--app-text-primary": "var(--color-terminal-light)",
    "--app-text-secondary": "var(--color-terminal-light-soft)",
    "--app-text-muted": "#718891",
    "--app-border-default": "var(--color-night-line)",
    "--app-border-strong": "var(--color-night-line-strong)",
    "--app-accent": "var(--color-signal-bright)",
    "--app-accent-soft": "rgba(93, 220, 241, 0.14)",
    "--app-accent-hover": "#85e8f7",
    "--app-accent-focus": "var(--color-signal-bright)",
    "--app-status-playing": "var(--color-signal-bright)",
    "--app-status-won": "var(--color-success-bright)",
    "--app-status-dead": "var(--color-danger-bright)",
    "--app-terminal-glow": "rgba(93, 220, 241, 0.1)",
  },
});
